## Problem 1

In [21]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize
from sklearn import preprocessing

In [14]:
df = np.array([[1,2,0], #creating dataframe
                  [0,1,1],
                  [5,6,6]])

In [15]:
print (df.shape)

(3, 3)


In [17]:
## 1. Replace each o with the mean of the non-zero values in its column 
## (it's guaranteed that there are at least two different non-zero values in each column)

n = df == 0
means = np.ma.array(df, mask = n).mean(1)
df + n * means.data[:,None]

array([[1. , 2. , 1.5],
       [1. , 1. , 1. ],
       [5. , 6. , 6. ]])

In [26]:
#normalize matrix by columns
x_normed = normalize(df, axis=0, norm='l1')

print(x_normed) #not getting result using l1

[[0.16666667 0.22222222 0.        ]
 [0.         0.11111111 0.14285714]
 [0.83333333 0.66666667 0.85714286]]


In [22]:
prep = preprocessing.scale(df) #using Sklearn.preprocessing ----- for Standardization, or mean removal and variance scaling¶

In [23]:
prep

array([[-0.46291005, -0.46291005, -0.88900089],
       [-0.9258201 , -0.9258201 , -0.50800051],
       [ 1.38873015,  1.38873015,  1.3970014 ]])

In [24]:
prep.mean(axis=0)  #The mean value of each column is 0

array([0., 0., 0.])

In [25]:
 prep.std(axis=0) #The standard deviation of the values of each column is 1 

array([1., 1., 1.])

## Problem 2

In [64]:
import json
import re
import requests

In [ ]:
# response = requests.get("https://........") <<<<----- Testing for API Endpoint ----->>>>
# data = json.loads(response.text)

In [ ]:
# data == response.json()
# type(data)

In [54]:
json_string = """
{
        "id": "1",
        "agent": "Radulf Katlego",
        "unit": "#3",
        "description": "This luxurious studio apartment 1 is in the heart of downtown.",
        "num_bedrooms": 1
}
"""

In [55]:
data 

[{'id': '1',
  'agent': 'Radulf Katlego',
  'unit': '#3',
  'description': 'This luxurious studio apartment is in the heart of downtown.',
  'num_bedrooms': 1}]

In [56]:
data = json.loads('[{}]'.format(json_string.replace("}\n{", "},\n{")))
values = [n["description"] for n in data if 'description' in n]
print(values)

['This luxurious studio apartment 1 is in the heart of downtown.']


In [ ]:
# planning to implement NLP/ Regex on <<< description >>>

In [57]:
nums = re.compile(r"[+-]?\d+(?:\.\d+)?")

In [61]:
nums.search("Beautiful 1-bedroom apartment with nearby yoga studio.").group(0)

'1'

In [63]:
nums.search("Beautiful studio with a nearby art studio.").group(0)

AttributeError: 'NoneType' object has no attribute 'group'

In [62]:
# if re.search is +ve we'll update the same in 'num_bedrooms':------ //// else 'num_bedrooms': become '0'

In [65]:
by_id ={}

In [66]:
# Increment complete TODOs count for each user.
for c in data:
    if c["unit"]:
        try:
            # Increment the existing user's count.
            by_id[c["id"]] += 1
        except KeyError:
            # This user has not been seen. Set their count to 1.
            by_id[c["id"]] = 1

In [67]:
by_id = sorted(by_id.items(), 
                   key=lambda x: x[1], reverse=True)

In [68]:
max_complete = by_id[0][1]

In [69]:
users = []
for user, num_complete in by_id:
    if num_complete < max_complete:
        break
    users.append(str(user))

max_users = " and ".join(users)